---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      ##maxSurge means, how many extra pods may run during the deployment
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdateselector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: quay.io/stefanprodan/podinfo:3.0.0
        ports:
        - containerPort: 3000
